-- Active: 1719148717285@@127.0.0.1@3306@github
CREATE TABLE USERS(
	uid INT NOT NULL AUTO_INCREMENT,
	uname VARCHAR(20) NOT NULL UNIQUE,
	pwd VARCHAR(256) NOT NULL,
	tel VARCHAR(20),
	email VARCHAR(30),
	PRIMARY KEY(uid)
);

CREATE TABLE LOGIN (
	uid INT NOT NULL,
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ip VARCHAR(20),
	device VARCHAR(20),
	PRIMARY KEY(uid, time),
	FOREIGN KEY(uid) REFERENCES USERS(uid),
	INDEX(uid, time)
);

CREATE TABLE ACCOUNT (
	uid INT NOT NULL,
	aid INT NOT NULL AUTO_INCREMENT,
	reg_date DATETIME NOT NULL,
	alevel INT NOT NULL,
	PRIMARY KEY(aid),
	FOREIGN KEY(uid) REFERENCES USERS(uid)
);

CREATE TABLE CHARACTERS (
    cid INT NOT NULL AUTO_INCREMENT,
    cname VARCHAR(20) NOT NULL,
	cimg VARCHAR(100) NOT NULL,
    sk_1 VARCHAR(30),
    sk_2 VARCHAR(30),
    sk_3 VARCHAR(30),
    talent VARCHAR(30),
    catk_0 INT NOT NULL,
    cdef_0 INT NOT NULL,
    chp_0 INT NOT NULL,
    cblk INT NOT NULL,
    PRIMARY KEY(cid)
);

CREATE TABLE ACC_CHAR(
	aid INT NOT NULL,
	cid INT NOT NULL,
	clevel INT NOT NULL,
	cpotent INT NOT NULL,
	PRIMARY KEY(aid, cid),
	FOREIGN KEY(aid) REFERENCES ACCOUNT(aid),
	FOREIGN KEY(cid) REFERENCES CHARACTERS(cid),
	INDEX(aid, cid)
);

CREATE TABLE BATTLE(
	bid INT NOT NULL AUTO_INCREMENT,
	bname VARCHAR(50) NOT NULL,
	map VARCHAR(100),
	PRIMARY KEY(bid)
);

CREATE TABLE EVENT(
	vid INT NOT NULL AUTO_INCREMENT,
	aid INT NOT NULL,
	bid INT NOT NULL,
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	pass_state INT NOT NULL,
	PRIMARY KEY(vid),
	FOREIGN KEY(aid) REFERENCES ACCOUNT(aid),
	FOREIGN KEY(bid) REFERENCES BATTLE(bid)
);

CREATE TABLE TEAM(
	vid INT NOT NULL UNIQUE,
	cid_1 INT,
	cid_2 INT,
	cid_3 INT,
	cid_4 INT,
	cid_5 INT,
	cid_6 INT,
	sk_1 INT,
	sk_2 INT,
	sk_3 INT,
	sk_4 INT,
	sk_5 INT,
	sk_6 INT,
	PRIMARY KEY(vid),
	FOREIGN KEY(vid) REFERENCES EVENT(vid)
);

CREATE TABLE ENEMY(
	eid INT NOT NULL AUTO_INCREMENT,
	ename VARCHAR(50) NOT NULL,
	eatk INT NOT NULL,
	edef INT NOT NULL,
	ehp INT NOT NULL,
	PRIMARY KEY(eid)
);

CREATE TABLE APPEAR(
	bid INT NOT NULL,
	eid INT NOT NULL,
	num INT NOT NULL,
	PRIMARY KEY(bid, eid),
	FOREIGN KEY(bid) REFERENCES BATTLE(bid),
	FOREIGN KEY(eid) REFERENCES ENEMY(eid),
	INDEX(bid, eid)
);